#Using PostgreSQL Configuration in Production

spring.datasource.url=jdbc:postgresql://dpg-d3rt6d8dl3ps7393stqg-a.singapore-postgres.render.com/fyndatabase
spring.datasource.username=fyndatabase_user
spring.datasource.password=ORT9otVC4hahLMAtnqHC18r8XpQPYrRM