#Using PostgreSQL Configuration in Production

spring.datasource.url=jdbc:postgresql://fyndatabase_user:cBzCRgr6WAr7Nha4mJqYXEwZdaNsVRsN@dpg-d8she1ojs32c73d5ga50-a/fyn_1z4c
spring.datasource.username=fyndatabase_user
spring.datasource.password=cBzCRgr6WAr7Nha4mJqYXEwZdaNsVRsN